export const routes = {
  notFound: "*",
  successfulPurchase: "/successful-purchase",
  login: "/login",
  registration: "/registration",
  home: "/home",
  shop: "/shop",
  product: "/product",
  cart: "/cart",
  contact: "/contact",
  admin: "/admin",
  productsActions: "/admin/products-actions",
  addNewProduct: "/admin/products-actions/add-new-product",
  categoriesActions: "/admin/categories-actions",
  addNewCategory: "/admin/categories-actions/add-new-category",
};
